version: '3'

services:
  ollama:
    build: .
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    ports:
      - "3000:8080"
    environment:
      - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
